version: "3.5"
services:
  # mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
        - ./mysql:/var/lib/mysql
    networks:
      - starter_net

  # temporal
  temporal:
    image: temporalio/auto-setup:0.30.0
    ports:
     - "7233:7233"
    environment:
      - "AUTO_SETUP=true"
      - "DB=mysql"
      - "MYSQL_USER=root"
      - "MYSQL_PWD=root"
      - "MYSQL_SEEDS=mysql"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - mysql
    networks:
      - starter_net

  # temporal-admin-tools
  temporal-admin-tools:
    image: temporalio/admin-tools:0.30.0
    stdin_open: true
    tty: true
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7233"
    depends_on:
      - temporal
    networks:
      - starter_net

  # temporal-web
  temporal-web:
    image: temporalio/web:0.30.0
    environment:
      - "TEMPORAL_GRPC_ENDPOINT=temporal:7233"
      - "TEMPORAL_PERMIT_WRITE_API=true"
    ports:
      - "8088:8088"
    depends_on:
      - temporal
    networks:
      - starter_net

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.18.1
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250"
    networks:
      - starter_net

networks:
  starter_net:
    name: starter_network

