env: local
mode: debug
databases:
  - name: starter_db
    type: mysql
    connection_string: root:root@tcp(localhost:3306)/starter_db?charset=utf8&parseTime=true&multiStatements=true&timeout=60s
    is_migrated: true
redis:
  cluster_mode: false
  addresses:
    - "localhost:6379"
  password:
  max_retries: 1
  pool_size_per_node: 2
  db: 1
temporal:
  address: "localhost:7233"
jaeger:
  advertise_addr: http://localhost:14268/api/traces
logs:
  - name: clog
    type: console
    min_level: debug
bff:
  http_bind: ":10080"
  http_advertise_addr: "localhost:10080"
event:
  grpc_bind: "localhost:10010"
  grpc_advertise_addr: "localhost:10010"
wallet:
  grpc_bind: ":10020"
  grpc_advertise_addr: "localhost:10020"
